#!/usr/bin/env python3
"""Write simulation configs for a subset of the configured UAVs.

Usage: select_uavs.py <config_dir> <out_dir> uav1 [uav2 ...]

Copies every file of <config_dir> to <out_dir>, keeping in simulator.yaml and network_config.yaml
only the selected UAVs. Used by ../../up.sh when SIM_UAVS is set.
"""
import shutil
import sys
from pathlib import Path

import yaml


def main() -> None:
    config_dir, out_dir, uavs = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3:]
    simulator = yaml.safe_load((config_dir / "simulator.yaml").read_text())
    network = yaml.safe_load((config_dir / "network_config.yaml").read_text())

    unknown = [u for u in uavs if u not in simulator["uav_names"] or u not in network["network"]["robot_names"]]
    if not uavs or unknown:
        sys.exit(f"select_uavs: {unknown or 'no UAVs'} not in {config_dir}/simulator.yaml and network_config.yaml")

    if out_dir.exists():
        shutil.rmtree(out_dir)
    shutil.copytree(config_dir, out_dir)

    for name in simulator["uav_names"]:
        if name not in uavs:
            simulator.pop(name, None)
    simulator["uav_names"] = uavs
    network["network"]["robot_names"] = uavs

    header = f"# generated by select_uavs.py from {config_dir} for: {' '.join(uavs)}\n"
    (out_dir / "simulator.yaml").write_text(header + yaml.safe_dump(simulator, sort_keys=False))
    (out_dir / "network_config.yaml").write_text(header + yaml.safe_dump(network, sort_keys=False))
    print(f"select_uavs: {out_dir} for {' '.join(uavs)}")


if __name__ == "__main__":
    main()
